version: '3'

services:
  memcached:
    image: memcached:1.4

  redis:
    image: redis:3.2-alpine

  postgres:
    image: postgres:9.5
    volumes:
      - postgres-data:/var/lib/postgresql/data

  web:
    build: ./docker/sentry
    depends_on:
      - memcached
      - redis
      - postgres
    environment:
      SENTRY_SECRET_KEY: "${SENTRY_SECRET_KEY}"
      SENTRY_MEMCACHED_HOST: memcached
      SENTRY_REDIS_HOST: redis
      SENTRY_POSTGRES_HOST: postgres
    ports:
      - 9090:9000
    volumes:
      - sentry-data:/var/lib/sentry/files

  cron:
    build: ./docker/sentry
    depends_on:
      - web
    command: run cron
    environment:
      SENTRY_SECRET_KEY: "${SENTRY_SECRET_KEY}"
      SENTRY_MEMCACHED_HOST: memcached
      SENTRY_REDIS_HOST: redis
      SENTRY_POSTGRES_HOST: postgres
    volumes:
      - sentry-data:/var/lib/sentry/files

  worker:
    build: ./docker/sentry
    depends_on:
      - web
    command: run worker
    environment:
      C_FORCE_ROOT: 1
      SENTRY_SECRET_KEY: "${SENTRY_SECRET_KEY}"
      SENTRY_MEMCACHED_HOST: memcached
      SENTRY_REDIS_HOST: redis
      SENTRY_POSTGRES_HOST: postgres
    volumes:
      - sentry-data:/var/lib/sentry/files

volumes:
  postgres-data:
    driver: local
  sentry-data:
    driver: local
